Refatoracao listagens
fga-eps-mds/2022-1-PUMA-Frontend pull request #35
Opened 2022-09-12 22:24 UTC by Bruno-Felix

## Descrição

## Issue

## Principais Implementações

## Tipos de Mudanças
 - [ ] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [ ] Documentação

2022-09-13 14:20 UTC, enzoggqs requested changes
<img width="747" alt="image" src="https://user-images.githubusercontent.com/38733364/189925835-c20c8edb-3b72-4b37-b92c-f9c4da071b31.png">
Olha como estão os botões na listagem de palavras chave

2022-09-13 14:21 UTC, enzoggqs commented
<img width="773" alt="image" src="https://user-images.githubusercontent.com/38733364/189926275-2ad75bdc-feba-4c7e-8523-0cb9472464fd.png">
Também acho que os cabeçalhos das tabelas poderiam ter uma fonte maior

2022-09-13 21:04 UTC, Bruno-Felix commented
> <img alt="image" width="773" src="https://user-images.githubusercontent.com/38733364/189926275-2ad75bdc-feba-4c7e-8523-0cb9472464fd.png">
> 
> Também acho que os cabeçalhos das tabelas poderiam ter uma fonte maior

Nesse mesmo print tem uma implementação que eu não fiz.
Acredito inclusive que a visualização do usuário logado foi você que fez.
Não está na branch errada?

2022-09-13 22:32 UTC, enzoggqs commented
> > <img alt="image" width="773" src="https://user-images.githubusercontent.com/38733364/189926275-2ad75bdc-feba-4c7e-8523-0cb9472464fd.png">
> > Também acho que os cabeçalhos das tabelas poderiam ter uma fonte maior
> 
> Nesse mesmo print tem uma implementação que eu não fiz. Acredito inclusive que a visualização do usuário logado foi você que fez. Não está na branch errada?

Pior que eu tava na branch certa, mas acho que deu algum problema de cache, não sei...

2022-09-13 22:34 UTC, enzoggqs approved these changes

2022-09-14 13:55 UTC, codehg approved these changes
Aprovado

2022-09-14 18:04 UTC, merged