[#70] Validar Nome da Disciplina no Cadastro
fga-eps-mds/2022-1-PUMA-Frontend pull request #5
Opened 2022-07-22 03:23 UTC by bhsouza

## Descrição

Inserindo mínimo de 10 caracteres do campo nome da disciplina

## Issue

Closes [#70](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/issues/70)

## Tipos de Mudanças
 - [x] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [ ] Documentação

2022-07-22 15:30 UTC, Bruno-Felix commented
**Detalhe percebido durante a solução desse bug:** [Comentário - Bugfix](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/issues/70#issuecomment-1192688667)

2022-07-22 18:36 UTC, enzoggqs approved these changes
Good job!

2022-07-22 18:39 UTC, enzoggqs requested changes
Corrigir o artigo na mensagem de erro

2022-07-25 02:45 UTC, Bruno-Felix commented
> Corrigir o artigo na mensagem de erro

Issue criada mas não pode ser trabalhada dentro dessa issue.

2022-07-25 23:17 UTC, codehg approved these changes
Correto!

2022-07-25 23:32 UTC, enzoggqs approved these changes

2022-07-25 23:32 UTC, merged